name: Python Style Checks

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx darglint

    - name: Generate documentation
      run: |
        sphinx-apidoc -o docs/ .
        sphinx-build -b html docs/ docs/_build

    - name: Check docstrings
      run: |
        darglint .